name: tensoflowanfis-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  # - pip   # not needed currently
  - tensorflow=2.3
  - numpy=1.18.1
  - pandas>=1.0.0
  - matplotlib==3.1.3
  - scikit-learn=0.22.1
  - seaborn=0.10.0
